language: bash

addons:
  apt:
    packages:
    - shellcheck
    sources:
    - debian-sid # Grab ShellCheck from the Debian repo
	
script:
  - shellcheck pre-commit sha256-update.sh update-golang.sh
