language: bash

sudo: required

before_install:
  - curl https://ftp-master.debian.org/keys/archive-key-7.0.asc | sudo apt-key add -
  - echo "deb http://ftp.us.debian.org/debian unstable main contrib non-free" | sudo tee -a /etc/apt/sources.list
  - sudo apt update -qq
  - sudo apt install shellcheck -y
  - sudo apt remove golang-go

script:
  - export GOROOT=
  - echo GOROOT=$GOROOT
  - ./shellcheck.sh
  - sudo DEBUG=1 ./update-golang.sh
  - sudo DEBUG=1 ./update-golang.sh
  - ls -al /usr/local
  - sudo DEBUG=1 ./update-golang.sh remove
  - ls -al /usr/local
